Update multidisabler

diff --git a/recovery/root/system/bin/multidisabler b/recovery/root/system/bin/multidisabler
--- a/recovery/root/system/bin/multidisabler
+++ b/recovery/root/system/bin/multidisabler
@@ -22,18 +22,19 @@ file_changed() {
 
 resize_vendor() {
   local dm_block=$(df -k | cat | grep "/vendor" | cut -d' ' -f1)
+  local old_blocks=$(df -k | cat | grep "/vendor" | cut -d' ' -f6)
+  local new_blocks=$(($old_blocks + 10110240))
 
   echo " - Unmounting /vendor..."
   umount /vendor
   echo " - Checking vendor block parition before resizing..."
   e2fsck -f $dm_block
-  echo " - Resizing the filesystem on $dm_block..."
-  resize2fs $dm_block
+  echo " - Resize - Recommended size (old size+10MB)..."
+  resize2fs $dm_block $new_blocksK
   echo " - Make the partition R/W by unsharing its blocks..."
   e2fsck -E unshare_blocks $dm_block
-  echo " - Remounting /vendor..."
-  mount /vendor
-  mount -o remount,rw /vendor
+  echo " - Run multidisabler again!"
+  exit 1
 }
 
 vendor_free_size_check() {
@@ -46,6 +47,7 @@ vendor_free_size_check() {
     echo " "
     rm -f /vendor/test
     resize_vendor
+    exit 1
   fi
 }
 
@@ -53,15 +55,18 @@ disable_fbe() {
   local md5
   local i
   fstab_files=`grep -lr 'fileencryption' vendor/etc`
+  echo " - Disabling file-based encryption (FBE) for /data..."
 
-  #
-  # Exynos devices = fstab.exynos*.
-  # MediaTek devices = fstab.mt*.
-  # Snapdragon devices = fstab.qcom, fstab.emmc, fstab.default
+  # S20/N20 range = fstab.exynos990.
+  # S10 range = fstab.exynos9820.
+  # Note 10 range = fstab.exynos9825.
+  # A[124]0 range = fstab.exynos7885.
+  # A50 = fstab.exynos9610.
+  # Tab A 10.1 range = fstab.exynos7885.
+  # Snapdragon devices = fstab.qcom.
   #
   for i in $fstab_files; do
     if [ -f $i ]; then
-      echo " - Disabling file-based encryption (FBE) for /data..."
       echo " -   Found $i."
       md5=$( md5 $i )
       # This comments out the offending line and adds an edited one.
@@ -100,11 +105,11 @@ disable_recovery_restoration() {
 
   echo " - Disabling restoration of stock recovery..."
 
-  for i in $ANDROID_ROOT $ANDROID_ROOT/system /vendor; do
+  for i in $ANDROID_ROOT $ANDROID_ROOT/system; do
     if [ -f $i/$r~ ]; then
-	echo " -   ...already disabled."
-	found=true
-	break
+  echo " -   ...already disabled."
+  found=true
+  break
     fi
 
     if [ -f $i/$r ]; then
@@ -112,9 +117,9 @@ disable_recovery_restoration() {
       mv $i/$r $i/$r~
 
       if [ -f $i/$r~ ]; then
-	echo " -     ...succeeded."
+  echo " -     ...succeeded."
       else
-	echo " -     ...failed."
+  echo " -     ...failed."
       fi
 
       found=true
@@ -130,6 +135,7 @@ echo " "
 echo "Multi-disabler v3.1 for Samsung devices"
 echo "running Android 9 or later."
 echo "by Ian Macdonald, enhanced by afaneh92"
+echo
 echo " "
 
 os=$(getprop ro.build.version.release)
